---
- name: Hardening and Verification Playbook
  hosts: my_servers
  become: yes
  tasks:
    - name: Create admin user
      user:
        name: admin
        shell: /bin/bash
        state: present
        groups: wheel
        append: yes

    - name: Disable Root Login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: restart ssh

    - name: Ensure Password Authentication is Disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: restart ssh

    - name: Set a custom Welcome Banner (MOTD)
      copy:
        dest: /etc/motd
        content: |
          **************************************************
          WELCOME TO SECURE SERVER: Managed by Jenkins/Ansible
          Authorized Access Only!
          **************************************************
