---
- name: secure ssh and admin user
  hosts: my_servers
  become: yes
  tasks:
    - name: create admin user
      user:
        name: admin
        shell: /bin/bash
        state: present

    - name: add admin user to sudo group
      user:
        name: admin
        groups: sudo
        append: yes
    
    - name: change the ssh port to 2222
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port 22'
        line: 'Port 2222'
      notify: restart ssh

  handlers:
      - name: restart ssh
        service:
          name: ssh
          state: restarted
